config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/SQAaaS:
      branch: master
      repo: https://github.com/EOSC-synergy/SQAaaS
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/SQAaaS git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-copper-pig.sh
        container: qc.acc_nerdy-sepia-oyster
  QC.Doc:
    repos:
      github.com/EOSC-synergy/SQAaaS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-olivine-bear.sh
        container: qc.doc_smelly-yellow-flounder
      github.com/EOSC-synergy/SQAaaS git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-auburn-mammoth.sh
        container: qc.doc_skinny-white-cat
      github.com/EOSC-synergy/SQAaaS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-chocolate-starfish.sh
        container: qc.doc_pokey-alizarin-macaw
  QC.Lic:
    repos:
      github.com/EOSC-synergy/SQAaaS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-blue-newfoundland.sh
        container: qc.lic_gamy-chocolate-dalmatian
  QC.Sty:
    repos:
      github.com/EOSC-synergy/SQAaaS hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-flax-gharial.sh
        container: qc.sty_geeky-lilac-barb
  QC.Ver:
    repos:
      github.com/EOSC-synergy/SQAaaS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pear-numbat.sh
        container: qc.ver_goopy-linen-retriever
timeout: 1800
